
[[constraint]]
  name = "github.com/satori/go.uuid"
  revision = "b2ce2384e17bbe0c6d34077efa39dbab3e09123b"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[prune]
  go-tests = true
  unused-packages = true
